ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS source_paths TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB;
