ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS summary TEXT NOT NULL DEFAULT '';

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS referential_keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS depends_on TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS related TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS confidence VARCHAR(16) NOT NULL DEFAULT 'medium';

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS review_status VARCHAR(32) NOT NULL DEFAULT 'pending';
